# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kelly Littlepage
author: Kelly Littlepage
display_title: Misapplied Math
subtitle: "Trading, Data Science, CS."
description: >
  The website of Kelly Littlepage. Content on finance, trading, HFT, math, 
  data science, coding, and technology.
baseurl: ""
url: "https://www.klittlepage.com"
titlecase: true
date_format: "ordinal"
permalink: /:year/:month/:day/:title/
exclude: ['Gemfile', 'Gemfile.lock']

twitter_username: kellylittlepage
github_username:  klittlepage
enable_rss: true
subscribe_rss: /feed.xml

# Build settings
markdown: kramdown
highlighter: pygments
category_dir: categories
kramdown:
  extensions:
    - autolink
    - footnotes
    - smart

code_dir: '_resources'

gems:
  - jekyll-paginate
  - octopress-paginate
  - octopress-render-code
  - octopress-codeblock
  - octopress-codefence
  - octopress-escape-code
  - octopress-gist
  - octopress-quote-tag
  - octopress-filters
  - octopress-date-format
  - octopress-debugger

paginate: 3
paginate_path: "/page/:num"
recent_posts: 5
excerpt_link: "Read on &rarr;"

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

gallery_dir: visualizations
paginate_gallery: 6
paginate_gallery_path: "/page/:num"

navigation:
- text: Blog
  url: /index.html
- text: Archives
  url: /archives/
- text: Categories
  url: /categories.html
- text: Visualizations
  url: /visualizations/
- text: Following
  url: /reading-list.html
- text: About
  url: /about.html

# Github repositories
github_user: klittlepage
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Linkedin user
linkedin_user: klittlepage

# Twitter
twitter_user: kellylittlepage
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: misappliedmath
disqus_show_comment_count: false

google_analytics_tracking_id: UA-43140702-1

facebook_like: false

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _images
    - _vendors/fonts
    - _vendors/images
    - _vendors/javascripts
    - _vendors/stylesheets
  compress:
    js: 'closure'
    css: 'yui_css'
  cachebust: hard 
  gzip: false